<a href="https://colab.research.google.com/github/Rashid-LDR/NLP-Project/blob/main/Natural_Language_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [44]:
import pandas as pd
import string, re
from textblob import TextBlob

In [45]:
path="/content/drive/MyDrive/NLP/IMDB_Dataset.csv"

In [46]:
df=pd.read_csv(path)

In [47]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49999    no one expects the star trek movies to be high...
50000    0        one of the other reviewers has mentio...
50001    0        one of the other reviewers has mentio...
50002    0        one of the other reviewers has mentio...
50003    0        one of the other reviewers has mentio...
Name: review, Length: 50004, dtype: object

In [48]:
def Remove_Html_tag(text):
  pattern=re.compile('<.*?>')
  return pattern.sub(r'',text)

In [49]:
df['review']=df['review'].apply(Remove_Html_tag)

In [50]:
df['review'].head()

0    one of the other reviewers has mentioned that ...
1    a wonderful little production. the filming tec...
2    i thought this was a wonderful way to spend ti...
3    basically there's a family where a little boy ...
4    petter mattei's "love in the time of money" is...
Name: review, dtype: object

In [51]:
exclude=string.punctuation
def Remove_punctutation(text):
  return text.translate(str.maketrans('','',exclude))

In [52]:
df['review']=df['review'].apply(Remove_punctutation)

In [53]:
df['review'][1]

'a wonderful little production the filming technique is very unassuming very oldtimebbc fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece the actors are extremely well chosen michael sheen not only has got all the polari but he has all the voices down pat too you can truly see the seamless editing guided by the references to williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece a masterful production about one of the great masters of comedy and his life the realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears it plays on our knowledge and our senses particularly with the scenes concerning orton and halliwell and the sets particularly of their flat with halliwells murals decorating every surface are terribly well done'

In [54]:
def Remove_Url(text):
  pattern_ulr=re.compile(r"https*?://\S+|www\.\S+")
  return pattern_ulr.sub(r'',text)

In [55]:
url1="This is my youtube channel url link : https://www.youtube.com/watch?v=6C0sLtw5ctc&list=PLKnIA16_RmvZo7fp5kkIth6nRTeQQsjfX&index=3  this is ATM"

In [56]:
url_clean=Remove_Url(url1)

In [57]:
chat_short_form={'AFAIK':'As Far As I Know',
'AFK':'Away From Keyboard',
'ASAP':'As Soon As Possible',
'ATK':'At The Keyboard',
'ATM':'At The Moment',
'A3':'Anytime, Anywhere, Anyplace',
'BAK':'Back At Keyboard',
'BBL':'Be Back Later',
'BBS':'Be Back Soon',
'BFN':'Bye For Now',
'B4N':'Bye For Now',
'BRB':'Be Right Back',
'BRT':'Be Right There',
'BTW':'By The Way',
'B4':'Before',
'B4N':'Bye For Now',
'CU':'See You',
'CUL8R':'See You Later',
'CYA':'See You',
'FAQ':'Frequently Asked Questions',
'FC':'Fingers Crossed',
'FWIW':'For What Its Worth',
'FYI':'For Your Information',
'GAL':'Get A Life',
'GG':'Good Game',
'GN':'Good Night',
'GMTA':'Great Minds Think Alike',
'GR8':'Great',
'G9':'Genius',
'IC':'I See',
'ICQ':'I Seek you',
'ILU': 'I Love You',
'IMHO':'In My Honest/Humble Opinion',
'IMO':'In My Opinion',
'IOW':'In Other Words',
'IRL':'In Real Life',
'KISS':'Keep It Simple, Stupid,',
'LDR':'Long Distance Relationship',
'LMAO':'Laugh My A.. Off',
'LOL':'Laughing Out Loud',
'LTNS':'Long Time No See',
'L8R':'Later',
'MTE':'My Thoughts Exactly',
'M8':'Mate',
'NRN':'No Reply Necessary',
'OIC':'Oh I See',
'PITA':'Pain In The A..',
'PRT':'Party',
'PRW':'Parents Are Watching',
'QPSA?':'Que Pasa?',
'ROFL':'Rolling On The Floor Laughing',
'ROFLOL':'Rolling On The Floor Laughing Out Loud',
'ROTFLMAO':'Rolling On The Floor Laughing My A.. Off',
'SK8':'Skate',
'STATS':'Your sex and age',
'ASL':'Age, Sex, Location',
'THX':'Thank You',
'TTFN':'Ta-Ta For Now!',
'TTYL':'Talk To You Later',
'U':'You',
'U2':'You Too',
'U4E':'Yours For Ever',
'WB':'Welcome Back',
'WTF':'What The F...',
'WTG':'Way To Go!',
'WUF':'Where Are You From?',
'W8':'Wait...',
'7K=Sick':'D Laugher',
'TFW' :'That feeling when. TFW internet slang often goes in a caption to an image.',
'MFW': 'My face when',
'MRW': 'My reaction when',
'IFYP': 'I feel your pain',
'LOL' :'Laughing out loud',
'TNTL' :'Trying not to laugh',
'JK': 'Just kidding',
'IDC':'I don’t care',
'ILY':'I love you',
'IMU':'I miss you',
'ADIH': 'Another day in hell',
'IDC': 'I don’t care',
'ZZZ': 'Sleeping, bored, tired',
'WYWH':'Wish you were here',
'TIME': 'Tears in my eyes',
'BAE': 'Before anyone else',
'FIMH':'Forever in my heart',
'BSAAW': 'Big smile and a wink',
'BWL': 'Bursting with laughter',
'LMAO': 'Laughing my a** off',
'BFF': 'Best friends forever',
'CSL': 'Can’t stop laughing',
}

In [58]:
def Chat_converstion(text):
  new_chat=[]
  for word in text.split():
    if word.upper() in chat_short_form:
      new_chat.append(chat_short_form[word.upper()])
    else:
      new_chat.append(word)
  return " ".join(new_chat)

In [59]:
Chat_converstion(url_clean)

'This is my youtube channel url link : this is At The Moment'

In [60]:

def Text_correction(text):
  text_blob=TextBlob(text)
  return text_blob.correct().string

In [65]:
Text_correction("Ths is a Conndittion")

'The is a Conndittion'